### ISSUE TITLE
Wacom Intuos S : cinnamon-settings wacom dumps core

### ISSUE THREAD

**Issue by wujastyk** [linuxmint/cinnamon-settings-daemon#294]
* csd version ('dpkg --list | grep cinnamon-settings-daemon' in Mint/Ubuntu)
```
ii  cinnamon-settings-daemon                   4.6.4+ulyana                                   amd64        daemon handling the Cinnamon session settings
```
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
```
Mint 20
```
 * Graphics hardware *and* driver used
```
Graphics:
  Device-1: Intel Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics 
  driver: i915 v: kernel 
  Display: x11 server: X.Org 1.20.8 driver: modesetting unloaded: fbdev,vesa 
  resolution: 1920x1080~60Hz, 1920x1080~60Hz 
  OpenGL: renderer: Mesa DRI Intel HD Graphics 4600 (HSW GT2) 
  v: 4.5 Mesa 20.0.8 

```

 * 32 or 64 bit
`64`

**Issue**

I have a Wacom Intuos S tablet.

Cannot start the cinnamon-settings wacom

**Steps to reproduce**

```
$ cinnamon-settings wacom 
Using PAM module (python3-pam)
/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py:426: DeprecationWarning: Gtk.Window.set_wmclass is deprecated
  self.window.set_wmclass(wm_class, wm_class)

(cinnamon-settings.py:218872): wacom-cc-panel-WARNING **: 19:47:20.625: Could not set the current stylus ID 0x0 for tablet 'Wacom Intuos S', no general pen found
**
wacom-cc-panel:ERROR:csd-wacom-device.c:1890:csd_wacom_device_set_current_stylus: assertion failed: (device->priv->styli)
Bail out! wacom-cc-panel:ERROR:csd-wacom-device.c:1890:csd_wacom_device_set_current_stylus: assertion failed: (device->priv->styli)
Aborted (core dumped)
```

**Expected behaviour**

Start wacom tablet settings menu.

**Other information**
